{
    "vinos"=[
        {
            "id":1,
            "imagen":"",//nombre de la imagen
            "nombre":"",//nombre del vino
            "descripcion":"",//descripcion corta para la pag de home
            "precio":,//precio real
            "bodega":"",//nombre de la bodega que lo elabora
            "region":"",// de donde es el vino
            "viñedo":"",//nombre del viñedo
            "crianza":"",//
            "notas de cata":"",// datos de color, sabor y textura
            "tipo de productos":"",//vino espumante, blanco o tinto
            "varietal":"",//tipo de uva
            "presentacion":"",//medida o cantidad de la botella
            "tiempo de crianza":"",   
            "info" :"",//informacion ampliada del vino
        },
        {
            "id":2,
            "imagen":"",
            "nombre":"",
            "descripcion":"",
            "precio":,
            "bodega":"",
            "region":"",
            "viñedo":"",
            "crianza":"",
            "notas de cata":"",
            "tipo de productos":"",
            "varietal":"",
            "presentacion":"",
            "tiempo de crianza":"",   
            "info" :"",
        },
        {
            "id":3,
            "imagen":"",
            "nombre":"",
            "descripcion":"",
            "precio":,
            "bodega":"",
            "region":"",
            "viñedo":"",
            "crianza":"",
            "notas de cata":"",
            "tipo de productos":"",
            "varietal":"",
            "presentacion":"",
            "tiempo de crianza":"",   
            "info" :"",
        },
        {
            "id":4,
            "imagen":"",
            "nombre":"",
            "descripcion":"",
            "precio":,
            "bodega":"",
            "region":"",
            "viñedo":"",
            "crianza":"",
            "notas de cata":"",
            "tipo de productos":"",
            "varietal":"",
            "presentacion":"",
            "tiempo de crianza":"",   
            "info" :"",
        },
        {
            "id":5,
            "imagen":"",
            "nombre":"",
            "descripcion":"",
            "precio":,
            "bodega":"",
            "region":"",
            "viñedo":"",
            "crianza":"",
            "notas de cata":"",
            "tipo de productos":"",
            "varietal":"",
            "presentacion":"",
            "tiempo de crianza":"",   
            "info" :"",
        },
        {
            "id":6,
            "imagen":"",
            "nombre":"",
            "descripcion":"",
            "precio":,
            "bodega":"",
            "region":"",
            "viñedo":"",
            "crianza":"",
            "notas de cata":"",
            "tipo de productos":"",
            "varietal":"",
            "presentacion":"",
            "tiempo de crianza":"",   
            "info" :"",
        },
        {
            "id":7,
            "imagen":"",
            "nombre":"",
            "descripcion":"",
            "precio":,
            "bodega":"",
            "region":"",
            "viñedo":"",
            "crianza":"",
            "notas de cata":"",
            "tipo de productos":"",
            "varietal":"",
            "presentacion":"",
            "tiempo de crianza":"",   
            "info" :"",
        },
        {
            "id":8,
            "imagen":"",
            "nombre":"",
            "descripcion":"",
            "precio":,
            "bodega":"",
            "region":"",
            "viñedo":"",
            "crianza":"",
            "notas de cata":"",
            "tipo de productos":"",
            "varietal":"",
            "presentacion":"",
            "tiempo de crianza":"",   
            "info" :"",
        },
        {
            "id":9,
            "imagen":"",
            "nombre":"",
            "descripcion":"",
            "precio":,
            "bodega":"",
            "region":"",
            "viñedo":"",
            "crianza":"",
            "notas de cata":"",
            "tipo de productos":"",
            "varietal":"",
            "presentacion":"",
            "tiempo de crianza":"",   
            "info" :"",
        },
        {
            "id":10,
            "imagen":"",
            "nombre":"",
            "descripcion":"",
            "precio":,
            "bodega":"",
            "region":"",
            "viñedo":"",
            "crianza":"",
            "notas de cata":"",
            "tipo de productos":"",
            "varietal":"",
            "presentacion":"",
            "tiempo de crianza":"",   
            "info" :"",
        },
        {
            "id":11,
            "imagen":"",
            "nombre":"",
            "descripcion":"",
            "precio":,
            "bodega":"",
            "region":"",
            "viñedo":"",
            "crianza":"",
            "notas de cata":"",
            "tipo de productos":"",
            "varietal":"",
            "presentacion":"",
            "tiempo de crianza":"",   
            "info" :"",
        },
        {
            "id":12,
            "imagen":"",
            "nombre":"",
            "descripcion":"",
            "precio":,
            "bodega":"",
            "region":"",
            "viñedo":"",
            "crianza":"",
            "notas de cata":"",
            "tipo de productos":"",
            "varietal":"",
            "presentacion":"",
            "tiempo de crianza":"",   
            "info" :"",
        }
    ]
}